id: P009209
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:28:09.563393
source_metadata:
  id: bdr:W1PD90128
  title: བཙན་ལྷ་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  volumes:
    22acdc1887c943d2afc85e7c82baa72b:
      image_group_id: I1PD90151
      title: ''
      volume_number: 1
      total_pages: 200
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
